// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZR_IHJB31ckwsE1DmbAXwStcZx-PsKYU',
    appId: '1:594218019146:web:bd05f6f331c950df12b9b3',
    messagingSenderId: '594218019146',
    projectId: 'new-push-notification-te-c8026',
    authDomain: 'new-push-notification-te-c8026.firebaseapp.com',
    storageBucket: 'new-push-notification-te-c8026.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZ8Nd-fIb6kwB0PMrgfbzApz7aftsgvcM',
    appId: '1:594218019146:android:c218d03ad3f2847012b9b3',
    messagingSenderId: '594218019146',
    projectId: 'new-push-notification-te-c8026',
    storageBucket: 'new-push-notification-te-c8026.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvA01mHh2Qbog9BbPSyOM6_WNiorIH2DQ',
    appId: '1:594218019146:ios:d3857dbd1a4736ce12b9b3',
    messagingSenderId: '594218019146',
    projectId: 'new-push-notification-te-c8026',
    storageBucket: 'new-push-notification-te-c8026.appspot.com',
    iosClientId: '594218019146-anjj06t0dni3q7dsaf4p7vb2d98k4egn.apps.googleusercontent.com',
    iosBundleId: 'com.example.newPushNotificationss',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvA01mHh2Qbog9BbPSyOM6_WNiorIH2DQ',
    appId: '1:594218019146:ios:451d77b0b8e89ef012b9b3',
    messagingSenderId: '594218019146',
    projectId: 'new-push-notification-te-c8026',
    storageBucket: 'new-push-notification-te-c8026.appspot.com',
    iosClientId: '594218019146-8ghmoa1lavdk8d7i9mm17kb4jnko0p12.apps.googleusercontent.com',
    iosBundleId: 'com.example.newPushNotification.RunnerTests',
  );
}
